### PR TITLE
Removing checkip.*

### PR DESCRIPTION
**Pull request by mtxadmin**
I suppose, this sort of sites are not dangerous in tracking perspective. Even if some javascript will try to make queries to them - from user side.

And two of them are closed.

(there are many of such sites still present in your list, but..)

### CODE REVIEW

**Comment by mtxadmin** [comment]
Hmm... EasyPrivacy list has db-ip.com though. Maybe #84, #85, #86 and #87 are doubtful, but I really can't imagine a scenario then IP->country geolocation (on user level, in client js) could compromise user privacy.

**Comment by ShadowWhisperer** [comment]
I have seen android apps, and malware call out to IP lookup domains. I search specifically for IP lookup domains, when adding to the _Tracker_ list. There are a ton.

https://github.com/ShadowWhisperer/BlockLists/issues/10

**Comment by mtxadmin** [comment]
Ok, I can imagine using one of such services in malicious code - for instance, to wipe or not information based on geolocation. I still think that is still way too overkill, but ok, I understand. Decline my pull requests then, please.

**Comment by ShadowWhisperer** [comment]
I monitor several honeypots (worldwide). It seems like the bitcoin mining bots use it more than anything else.

**Comment by spirillen** [comment]
Just a comment on this thread as I tested the records with pyfunceble, about 50% of them seems unresponsive

```python
Subject                                                                                              Status      Source     Expiration Date   Registrar                      HTTP Code  Checker      
---------------------------------------------------------------------------------------------------- ----------- ---------- ----------------- ------------------------------ ---------- -------------
checkip.0c75897459d0b08e9899e474005a29a68369aa83.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY 
checkip.0396a36ee7822c443e15214fc1fd4ed4938b51c7.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.1429a24ab24eaaa3fbc1358998a10e0227abea8e.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.1e4e17cd9947c741d37dd85ab7522265e3d2cab2.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.237910a875f588f3b7456df57cedc8155019721c.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.29db1945fc2279eea6d2992b63dee29951b366a0.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.35b97fc931c405b321bfbfdb7972f98885922d0e.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.399257f9735d70f5ab96012c663830e900e76446.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.3fd1a035de8b8bd97b2a2f31e3e2a8aa18b3ce3e.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.423adfa8aa3ab0d30ad4d92fb19e3ffb6ac432d7.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.4cd6a4a5a32daacf8f7819b4f907152fcb41c812.com                                                 ACTIVE      DNSLOOKUP  Unknown           Unknown                        301        AVAILABILITY
checkip.448ff99c69e35a998730b495aee17aa92d277293.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.669abe7ac42273c9610169936d40488c138e9bf0.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.67de40a266207d950d17635a0deb7cc448cd4c56.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.6855c28475e3e125092688d11e4c57557e3d2401.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.6db251bafd0f937da027859ccac639e0aec5ff79.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.71b9ddb3e8177ae2913047f27da67a0d12defea1.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.76ad9f2de7a6e80b9b377b1b025b70275b5dea22.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.79fb3e6b18c92c34e6edaf2ed806fcb8ec1c89ec.com                                                 ACTIVE      DNSLOOKUP  Unknown           Unknown                        301        AVAILABILITY
checkip.a20d92fa968cddc343ace96b8e8c7311c8da2150.com                                                 ACTIVE      DNSLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.ac4b9084a3ed7aa0dc570e144586de9ee5f14c59.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.acb7042f2f0b1e9ee2d9448628bb57fe4ad11894.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.amazonaws.com                                                                                ACTIVE      DNSLOOKUP  Unknown           Unknown                        200        AVAILABILITY
checkip.bbf3173cff62ec57b774503eefef4030f03ae946.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.c4ad95cb7848566f3a4eca27b89addd7a5fbdfc5.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.ccf505d88f571473a3dfba1aface67b693a62d3f.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.d571d4e00ea4765529703412b1045ba8079d9d87.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.deepstateplatypus.com                                                                        ACTIVE      DNSLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.dns.he.net                                                                                   ACTIVE      DNSLOOKUP  Unknown           Unknown                        200        AVAILABILITY
checkip.dy.fi                                                                                        ACTIVE      DNSLOOKUP  Unknown           Unknown                        200        AVAILABILITY
checkip.dyn.com                                                                                      ACTIVE      DNSLOOKUP  Unknown           Unknown                        200        AVAILABILITY
checkip.dyndns.it                                                                                    ACTIVE      DNSLOOKUP  Unknown           Unknown                        200        AVAILABILITY
checkip.dyndns.com                                                                                   ACTIVE      DNSLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.dyndns.org                                                                                   ACTIVE      DNSLOOKUP  Unknown           Unknown                        200        AVAILABILITY
checkip.e14e6c9db7dc4354c87acd5c4c41df951f31a5c1.com                                                 ACTIVE      DNSLOOKUP  Unknown           Unknown                        301        AVAILABILITY
checkip.e3cc65d3b5c5f4e0ccf935e55a03f2383cd9de6c.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.efafb68888c3d298b690354673a2bf901a7ea97f.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.eurodyndns.org                                                                               ACTIVE      DNSLOOKUP  Unknown           Unknown                        301        AVAILABILITY
checkip.fcec01dcdd91e81752ff8b552e3d278c1e7ca735.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.fd7ee2d40190de1fc427a9a991ef60917dd4b1b8.com                                                 INACTIVE    STDLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.fptplay.net                                                                                  ACTIVE      DNSLOOKUP  Unknown           Unknown                        200        AVAILABILITY
checkip.fdd6421ecd7df00cee88cb90b45c81148e843121.com                                                 ACTIVE      DNSLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.momo.vn                                                                                      ACTIVE      DNSLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.homeseer.com                                                                                 ACTIVE      DNSLOOKUP  Unknown           Unknown                        301        AVAILABILITY
checkip.safehats.com                                                                                 ACTIVE      DNSLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.spdns.de                                                                                     ACTIVE      DNSLOOKUP  Unknown           Unknown                        200        AVAILABILITY
checkip.synology.com                                                                                 ACTIVE      DNSLOOKUP  Unknown           Unknown                        200        AVAILABILITY
checkip.thaiware.com                                                                                 ACTIVE      DNSLOOKUP  Unknown           Unknown                        302        AVAILABILITY
checkip.totallyacdn.com                                                                              ACTIVE      DNSLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY
checkip.windscribe.com                                                                               ACTIVE      DNSLOOKUP  Unknown           Unknown                        301        AVAILABILITY
```

**Comment by ShadowWhisperer** [comment]
```
103.225.168.22  checkip.thaiware.com
104.20.93.59    checkip.windscribe.com
104.20.94.59    checkip.windscribe.com
104.21.11.25    checkip.fdd6421ecd7df00cee88cb90b45c81148e843121.com
104.21.31.88    checkip.a20d92fa968cddc343ace96b8e8c7311c8da2150.com
104.21.60.22    checkip.4cd6a4a5a32daacf8f7819b4f907152fcb41c812.com
104.21.60.232   checkip.e14e6c9db7dc4354c87acd5c4c41df951f31a5c1.com
104.21.76.202   checkip.79fb3e6b18c92c34e6edaf2ed806fcb8ec1c89ec.com
104.24.30.5     checkip.totallyacdn.com
104.24.31.5     checkip.totallyacdn.com
104.248.79.120  checkip.synology.com
104.26.4.147    checkip.deepstateplatypus.com
104.26.5.147    checkip.deepstateplatypus.com
118.69.184.28   checkip.fptplay.net
132.226.247.73  checkip.dyn.com
132.226.247.73  checkip.dyndns.com
132.226.247.73  checkip.dyndns.org
132.226.8.169   checkip.dyn.com
132.226.8.169   checkip.dyndns.com
132.226.8.169   checkip.dyndns.org
13.234.252.219  checkip.safehats.com
138.201.62.170  checkip.spdns.de
138.201.63.14   checkip.spdns.de
138.68.28.244   checkip.synology.com
142.93.81.166   checkip.synology.com
15.207.49.128   checkip.safehats.com
158.101.44.242  checkip.dyn.com
158.101.44.242  checkip.dyndns.com
158.101.44.242  checkip.dyndns.org
159.65.77.153   checkip.synology.com
159.89.129.146  checkip.synology.com
159.89.142.52   checkip.synology.com
165.227.63.200  checkip.synology.com
172.67.165.19   checkip.fdd6421ecd7df00cee88cb90b45c81148e843121.com
172.67.175.194  checkip.a20d92fa968cddc343ace96b8e8c7311c8da2150.com
172.67.187.187  checkip.4cd6a4a5a32daacf8f7819b4f907152fcb41c812.com
172.67.200.180  checkip.79fb3e6b18c92c34e6edaf2ed806fcb8ec1c89ec.com
172.67.202.30   checkip.e14e6c9db7dc4354c87acd5c4c41df951f31a5c1.com
172.67.72.20    checkip.deepstateplatypus.com
18.207.73.236   checkip.amazonaws.com
184.105.242.4   checkip.dns.he.net
193.122.130.0   checkip.dyn.com
193.122.130.0   checkip.dyndns.com
193.122.130.0   checkip.dyndns.org
193.122.6.168   checkip.dyn.com
193.122.6.168   checkip.dyndns.com
193.122.6.168   checkip.dyndns.org
206.189.214.49  checkip.synology.com
210.245.113.75  checkip.momo.vn
3.227.179.93    checkip.amazonaws.com
3.229.163.179   checkip.amazonaws.com
34.205.198.8    checkip.amazonaws.com
44.208.222.62   checkip.amazonaws.com
45.76.31.131    checkip.homeseer.com
54.236.209.169  checkip.amazonaws.com
54.72.170.27    checkip.dyndns.it
65.0.106.137    checkip.safehats.com
80.92.65.242    checkip.eurodyndns.org
85.188.1.23     checkip.dy.fi

```

**Pull request closed without merging**
